Typescript + mongo + docker + some implementation
sgghhh/hw-market-bot pull request #4
Opened 2020-09-14 00:06 UTC by vlakam

Сделано всё в тайпскрипте.
Сделан docker
Сделаны модели для монго.
Отказ.

Нужно сделать:
- Поддержку фото (пока только одного)
- Создание объявления через сцены в несколько шагов? (сейчас берется первая строчка объявления как заголовок)
- Принятие объявления
- Завершение лота
- Выделить отказ в общую часть и убрать повторение кода
- У deal надо заполнять reviewedBy

2020-09-14 06:38 UTC, sgghhh commented
тайпскрипт здесь зачем?

2020-09-14 06:56 UTC, sgghhh commented
зачем монго?
можно сделать без базы

2020-09-14 07:25 UTC, Kylmakalle requested changes

2020-09-14 07:25 UTC, Kylmakalle commented on docker-compose.yml
> +    #   - 27017:27017
```suggestion
        - 127.0.0.1:27017:27017
```

2020-09-14 07:25 UTC, Kylmakalle commented on src/handlers/Deny.ts
> +    if (!deal || deal.status !== DealStatus.REVIEW) return; // :DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
```
await ctx.telegram.answerCbQuery("Ашыбка") return;
```

2020-09-14 07:25 UTC, Kylmakalle commented on src/handlers/Message.ts
> +            `Извини, но твой лот "${deal.title}" не был одобрен модерацией.\nПричина: ${text}`,
Добавить возможность опускать причину

2020-09-14 07:25 UTC, Kylmakalle commented on src/models/User.ts
> +    surname?: string;
Может поля как из bot api?
surname == last_name, etc.

2020-09-14 07:25 UTC, Kylmakalle commented on src/models/User.ts
> +    deals!: Array<Deal>;
Тут ж будут id сделок или я глупый?

2020-09-14 07:25 UTC, Kylmakalle commented on src/models/User.ts
> +        return `${this.name} ${this.surname}`;
```suggestion
        if (typeof this.surname != 'undefined' && this.surname) {
            return `${this.name} ${this.surname}`;
        } else {
            return  `${this.name}`;
        }
```

2020-09-14 07:25 UTC, Kylmakalle commented on src/models/User.ts
> +        return `[${this.name} ${this.surname}](tg://user?id=${this.id}) [${this.getMentionById()}]`;
```suggestion
        return `[${this.getFullName()}](tg://user?id=${this.id}) [${this.getMentionById()}]`;
```

2020-09-14 09:53 UTC, vlakam commented on src/handlers/Message.ts
> +            `Извини, но твой лот "${deal.title}" не был одобрен модерацией.\nПричина: ${text}`,
Это уже есть, если нажать "говно"

2020-09-14 09:53 UTC, vlakam commented on src/models/User.ts
> +    surname?: string;
круто было бы

2020-09-14 09:53 UTC, vlakam commented on src/models/User.ts
> +    deals!: Array<Deal>;
да

2020-09-14 09:58 UTC, vlakam commented
> тайпскрипт здесь зачем?

В основном для удобства. Даже тот же самый бейбл не нужно прикручивать 



> зачем монго?
> можно сделать без базы

Насчет базы еще подумаем

2020-09-14 11:16 UTC, sgghhh commented
а кому JS не удобен в этом микроскопическом проекте?
babel уже был прикручен. 
Пока что сомнительные плюсы ты приводишь.

2020-09-14 11:20 UTC, vlakam commented
> Пока что сомнительные плюсы ты приводишь.
Это я делаю лучше всего по жизни

2020-09-14 11:36 UTC, sgghhh commented
докер можно отдельным мр завести, чтобы протолкнуть его в проект и забыть

с монго вопросы остаются. или у нас различается ведение конечного результата, которое мне донесли, или это оверхед

2020-09-14 18:24 UTC, vlakam commented
Bump
Мастер не двигается пока - предлагается писать сюда

В принципе всё реализовано, кроме разве что поддержки фотографий

2020-09-14 18:25 UTC, vlakam commented
Babel лютую дичь генерирует на async\await, которая отказывается запускаться в ноде, поэтому я его пока что снёс

2020-09-14 18:32 UTC, Kylmakalle approved these changes

2020-09-14 18:32 UTC, Kylmakalle commented on src/handlers/Accept.js
> +    const infoString = `${reviewMessageId}_${publishedMessageId}`;
Предлагаю в качестве общего стандарта делителей ввести `:`
В библиотеках на питоне такое используется

`_` встречается слишком часто в обычном тексте

2020-09-14 18:32 UTC, Kylmakalle commented on src/handlers/Accept.js
> +                return m.inlineKeyboard([m.callbackButton('Продано', `sold${infoString}`)], {});
разделить команаду `sold` и инфу

2020-09-14 18:32 UTC, Kylmakalle commented on src/handlers/Message.js
> +        const actualText = caption || text; // надо еще поддерживать заявки с фотографиями!!!
> надо еще поддерживать заявки с фотографиями!

Нативно или в telegra.ph/upload 🤔?

2020-09-14 18:32 UTC, Kylmakalle commented on src/models/User.js
> +        return `<a href="tg://user?id=${this.id}">${this.getFullName()}</a> [${this.getMentionById()}]`
Тут по-хорошему надо эскейпить, а то ⚰️⚰️💀🏳️‍🌈 

В telegraf должно быть

2020-09-14 18:35 UTC, Kylmakalle approved these changes

2020-09-14 18:46 UTC, vlakam commented
1. эскейп имени человека
2. кнопка отмены продажи (для продавана\модератора)
3. поддержка фотографий

2020-09-14 20:28 UTC, sgghhh commented
какие проблемы есть сейчас с бабелем? все еще с асинками?

2020-09-14 20:34 UTC, sgghhh commented
@Kylmakalle закрой пожалуйста те обсуждения, которые как ты считаешь, уже можно закрыть

2020-09-14 20:44 UTC, Kylmakalle approved these changes
👍  MVP ready @sgghhh @vlakam

2020-09-14 20:55 UTC, sgghhh reviewed
> какие проблемы есть сейчас с бабелем? все еще с асинками?

закомменти лучше, но не удаляй, если есть пока проблема

2020-09-14 20:55 UTC, sgghhh commented on docker-compose.yml
> +  mongo:
убрать компоуз, не нужен

2020-09-14 20:55 UTC, sgghhh commented on src/index.js
> +const init = async () => {
зачем этот блок в асинке?

2020-09-14 20:55 UTC, sgghhh commented on src/handlers/Sold.js
> +        await ctx.telegram.editMessageText(PUBLICATION_CHANNEL_ID, publishedMessageId, undefined, `<b>Продано</b>\n<s>${message.reply_to_message.text}</s>`, Extra.HTML());
разбей пж на две, очень длинная строка

2020-09-14 21:39 UTC, vlakam commented on src/index.js
> +const init = async () => {
Чтобы если вдруг бот не может стартануть то эксепшен полетел

2020-09-15 12:48 UTC, sgghhh approved these changes
@vlakam ок, спасибо

2020-09-15 12:50 UTC, merged